### PR TITLE
Updating specs related to job nd job configs 

### PR DESCRIPTION
**Pull request by kritika-singh3**
DNM: still work in progress

updated specs to use the mithril based page

### CODE REVIEW

**Comment by GaneshSPatil** [comment]
@kritika-singh3 - As each of these specs bring up a different server.  Globally enabling the pipeline config spa toggle is not possible.

We will be required to add `* enable pipeline config spa` step in each spec which enables enables the new pipeline config spa.

**Comment by kritika-singh3** [comment]
I though the PR https://github.com/gocd/gocd/pull/8035 removes the toggle check when rendering the new pipeline config spa.
Also, the specs load the page directly and not via edit button click.

**Comment by GaneshSPatil** [comment]
> I though the PR [gocd/gocd#8035](https://github.com/gocd/gocd/pull/8035) removes the toggle check when rendering the new pipeline config spa.

No. As mentioned in the readme, based on the toggle value, it will render either the old rails page or new pipeline config spa, when the pipeline settings icon is clicked.

> Also, the specs load the page directly and not via edit button click.

Okay Good. We might not need to worry about the toggle then.

**Comment by kritika-singh3** [comment]
I tried not to update the stage and pipeline settings url - but had to too much duplicity was getting introduced.
This will lead to breaking of many (almost all) specs. Will fix them little by little :)

**Pull request merged**
